# Generated by Django 2.1.2 on 2018-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.CharField(blank=True, help_text='options', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='display_name',
            field=models.CharField(blank=True, help_text='name', max_length=100, null=True),
        ),
    ]
