# Generated by Django 2.1.2 on 2018-12-05 21:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181205_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(help_text='Map ID', max_length=200)),
                ('props', django.contrib.postgres.fields.jsonb.JSONField(help_text='map props')),
            ],
        ),
    ]
