# Generated by Django 2.1.2 on 2018-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='level_type',
            field=models.CharField(blank=True, help_text='lvel type name from levelType', max_length=100, null=True),
        ),
    ]
