# Generated by Django 2.1.2 on 2018-12-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_field_level_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='level_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.LevelType'),
        ),
    ]
