# Generated by Django 2.1.2 on 2018-12-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181208_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='field_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Field'),
        ),
    ]
