# Generated by Django 2.1.2 on 2018-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_level_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTypeLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.FloatField(help_text='Type Id')),
                ('level', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='levels',
        ),
    ]
