# Generated by Django 2.1.2 on 2018-12-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181208_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltype',
            name='level_type_id',
            field=models.IntegerField(blank=True, help_text='level type id', null=True),
        ),
    ]
