# Generated by Django 2.1.2 on 2018-12-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_leveltype_level_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leveltypelevels',
            old_name='level_type_id',
            new_name='level_type',
        ),
    ]
