# Generated by Django 2.1.2 on 2018-12-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181208_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='field_id',
            new_name='field',
        ),
    ]
